# R02 Scientific Computation: Numerical Arrays with Numpy

Alexander Mervar  
2.1.2021  
COGS-Q 320

Link: [https://numpy.org/doc/stable/user/quickstart.html](https://numpy.org/doc/stable/user/quickstart.html)

### The Basics

In [2]:
import numpy as np
a = np.arange(25).reshape(5,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### Array Creation

In [5]:
a = np.array([2,3,4])
print(a)
print(np.zeros((3,4)))

[2 3 4]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Printing Arrays

See above for printing

### Basic Operations

In [11]:
a = np.linspace(0, 100, 11)
b = np.arange(11)
print(a)
print()
print(b)
print()
print(a-b)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]

[ 0  1  2  3  4  5  6  7  8  9 10]

[ 0.  9. 18. 27. 36. 45. 54. 63. 72. 81. 90.]


### Note:
The next few sections were pretty trivial so I skipped them to move to more uncomfortable areas that I needed more

## Changing the Shape of an Array

In [16]:
rg = np.random.default_rng(1)
a = np.floor(10*rg.random((3,4)))
print(a.shape)
print()
# Flatten the array
print(a.ravel())
print()
# Reshape the array to whatever dimensions desired
# print(a.reshape(7,2))
# print(a.reshape(6,1))
# Cannot reshape to an array size with difference in elements
print(a.reshape(6,2))

(3, 4)

[5. 9. 1. 9. 3. 4. 8. 4. 5. 0. 7. 5.]

[[5. 9.]
 [1. 9.]
 [3. 4.]
 [8. 4.]
 [5. 0.]
 [7. 5.]]


### Copies

A shallow copy does not allow you to work with the copy instead, it acts as a view. With a deep copy using the <code>.copy</code> method, you get a seperate array looking at different data that has the same data in the cells.

### Less Basic

In [19]:
a = np.arange(12).reshape(3,4)
b = a > 4
b                                          # b is a boolean with a's shape
# array([[False, False, False, False],
#       [False,  True,  True,  True],
#       [ True,  True,  True,  True]])
a[b]                                       # 1d array with the selected elements
# array([ 5,  6,  7,  8,  9, 10, 11])

a[b] = 0                                   # All elements of 'a' higher than 4 become 0
a
# array([[0, 1, 2, 3],
#       [4, 0, 0, 0],
#       [0, 0, 0, 0]])

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

### The ix_() Function

I was confused by this function and would like it explained in class

### The Remainder of this tutorial was trivial

## Notes


- **Ask about the ix_() function in class**
